### ISSUE TITLE
importing repository does not respect settings like `organization`, `base_url` and `token`

### ISSUE THREAD

**Issue by SpamapS** [terraform-providers/terraform-provider-github#225]
Hi there,

### Terraform Version
```$ terraform -v
Terraform v0.11.13
+ provider.github v2.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository

### Terraform Configuration Files
```hcl
provider "github" {
  alias        = "infra"
  organization = "infrastructure"
  base_url     = "https://REDACTED.someorg.test/api/v3/"
}

resource "github_membership" "infra-clint" {
  provider = "github.infra"
  username = "clint"
  role     = "admin"
}

resource "github_membership" "infra-tim" {
  provider = "github.infra"
  username = "tim"
  role     = "admin"
}

resource "github_repository" "infra-sandbox" {
  provider    = "github.infra"
  name        = "sandbox"
  description = "A place to play with gitops"
}

resource "github_branch_protection" "infra-sandbox-master" {
  provider   = "github.infra"
  repository = "${github_repository.infra-sandbox.name}"
  branch     = "master"

  required_pull_request_reviews {
    dismiss_stale_reviews = true
  }
}
```

### Debug Output

https://gist.github.com/SpamapS/7a3243984f21e79d4f2b010fa6347196

### Expected Behavior

The provider should have used my config values for `base_url` and `organization`, and should have read the token from `GITHUB_TOKEN`

### Actual Behavior

Provider seems to have ignored all of those.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create personal access token on github enterprise
2. `export GITHUB_TOKEN=<the_token>`
3. Ensure `base_url` is accurate to the same GitHub enterprise, and all listed users exist in GitHub enterprise (in example, `clint` and `tim`)
4. Create org on GitHub Enterprise (in example, `infrastructure`)
5. Create `sandbox` repo under org
6. `terraform apply` -- this should fail because repo already exists
7. `terraform import github_repository.infra-sandbox sandbox` -- asks for organization instead of using passed in org. 

### Important Factoids
- The debug output includes a lot from the S3+Dynamo backend that I use for state.
- Our GitHub enterprise is set up to refuse all access by unauthenticated users (which is pretty standard)

**Comment by SpamapS** [comment]
Tested and still happens with latest master, hash: 549388ba7eca4d99d4c94705c96e60c07e138936

**Comment by megan07** [comment]
Hi @SpamapS !

Thank you for submitting this issue.  I think what might be causing some confusion is the `alias` attribute that you are passing in to the provider.  One purpose for the `alias` attribute is for defining multiple provider instances with different configurations.  The default github provider does not have an alias, so when adding the `alias` attribute here, you are differentiating this new `infra` provider from the default one.  All of the resources defined in your configuration file specify the `github.infra` provider, so during `plan` and `apply`, it knows which github provider to write to and uses the associated credentials.  However, when importing from a provider, Terraform will default to reading from the default provider, which in this case doesn't have `organization` etc defined.  In order to import any of the resources in from your defined provider, you need to specify the `-provider=github.infra` flag on the command line.

Here are a couple of references that might help:
**Multiple Provider Instances** - https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances
**Import Provider Flag** - https://www.terraform.io/docs/commands/import.html#provider-provider

As such I am going to close this issue, but please don’t hesitate to reply or open a new issue if this is still an issue!

Thanks!
