### ISSUE TITLE
[Feature Request] support enabling and disabling vulnerability alerts

### ISSUE THREAD

**Issue by majormoses** [terraform-providers/terraform-provider-github#238]
Github (now) supports [enabling](https://developer.github.com/v3/repos/#enable-vulnerability-alerts) and [disabling](https://developer.github.com/v3/repos/#disable-vulnerability-alerts) Githubs vulnerability alerts settings on the repository.

The upstream golang library has merged support for this as of [v25.1.1](https://github.com/google/go-github/blob/v25.1.1/github/repos.go#L465-L497) and can be pulled in via #228.

It would be really great if we could enable this.

**Comment by biancarosa** [comment]
I'll give it a try on this one.

**Comment by tracypholmes** [comment]
Hi @biancarosa. We would be happy to accept a PR for this if you would like to open one. Looking forward to it, and let us know if you have any questions!

**Comment by tiesmaster** [comment]
I don't know if this should really a separate issue, but you can also [grant more people access to your security alerts](https://help.github.com/en/articles/managing-alerts-for-vulnerable-dependencies-in-your-organization). It'd be nice if you can also do that.

**Comment by kszarek** [comment]
@biancarosa are you going to work on this? I also need it for my Github automation.

**Comment by mwarkentin** [comment]
We could use this too. :)

**Comment by jtsaito** [comment]
Please see https://github.com/terraform-providers/terraform-provider-github/pull/382 . I hope it's okay I added the PR right away.

@biancarosa If you have meanwhile worked on a solution, I'm happy to drop my PR and go ahead with yours.

**Comment by jcudit** [comment]
@jtsaito - thanks for reviving this one.

Regarding the proposed implementation, I am in favour of this being a boolean on the existing `repository` resource, but will defer to what the majority of users feel about the configuration experience.  I think this issue would benefit from another PR that leverages a boolean instead of a new top-level resource.

Lets give @biancarosa until next week to respond as well as some time for the community to chime in on how this implementation should progress.

**Comment by jtsaito** [comment]
Submitted a PR with vulnerability alerts as an attribute on the repo resource: https://github.com/terraform-providers/terraform-provider-github/pull/444 .
