### ISSUE TITLE
Allow setting default_branch on create.

### ISSUE THREAD

**Issue by joestump** [terraform-providers/terraform-provider-github#38]
It appears in the code that you can't set `default_branch` on create; a sad limitation of the create API on GitHub it would seem. 

Is there any reason why `resourceGithubRepositoryUpdate` couldn't be called from `resourceGithubRepositoryCreate` _only_ in the case that `default_branch` is set to something other than `master`?

**Comment by grubernaut** [comment]
Hey @joestump, thanks for the issue! 

The primary reason that you cannot set the `default_branch` during a repository `Create`, is purely a limitation of `git` and not `GitHub`. The target reference to the new `default_branch` needs to be created prior to `GitHub` recognizing that the branch even exists in order to use that as the new default branch. 

In order to do this _during_ a "create" of the repository, a user would have to: 
- Create the repository via Terraform
- Using a local-exec provisioner: 
  - Clone the new repository
  - Create the new ref for the new target GitHub branch
  - Push the new ref
- Update the GitHub repository with the new `default_branch`

The GitHub API also limits specifying the `default_branch` on Create for this specific reason as well. Due to the complexity of changes required to be able to "set" the `default_branch` during a single `"Create"`, I opted to only allow users to set the `default_branch` once the repository has already been created. We could definitely call `Update` from the `Create` method, but the necessary reference to the new git branch wouldn't exist, and the Terraform run would fail every time during `Create`. Causing the user to perform the previously listed manual steps, then re-run Terraform to achieve the proper result. IMO it was a much nicer user experience to not error out on every repository `Create`, by simply preventing the population of that attribute until the repository had already been created. 

Hope this helps clear things up, and happy to discuss further if needed! For now, going to close this issue though.
