### ISSUE TITLE
Use "Squash and Merge" as default to merge commits to master

### ISSUE THREAD

**Issue by benj-fletch** [terraform-providers/terraform-provider-github#380]
I think that we should move to using the [Squash and Merge](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) option when merging all commits to master. This will keep the history tree clean while still preserving all the information which authors are committing to this repository.

This is a stylistic thing mostly and the following should be considered:
- Squashing rewrites history, so you lose fine grained reversion access to commits, though any
 commit with a tag will be retained in the history.

It's a low priority thing but personally I think it makes repos cleaner and easier to manage.

Thanks!

**Comment by patrickmarabeas** [comment]
It should be case by case. By squashing everything you loose fidelity into **why** particular changes were made in larger PRs. That said - that does rely upon good commits in the first place.

If squash merges are to be used, it should be called out the merger needs to rewrite the commit message to be meaningful and free of PR fixes, otherwise you end up with this sort of garbage commit:

```
Add some sort of feature (#315)

* add some sort of feature

* changes requested in PR

* changes requested in PR

* fix some bug

* changes requested in PR

* changes requested in PR

* update tests
```

**Comment by jcudit** [comment]
This is now happening.  Thanks for the guidance here.
