### ISSUE TITLE
Acceptance test runs failing at `match pattern` step for labels not prefixed by `acceptance-test`

### ISSUE THREAD

**Issue by anGie44** [terraform-providers/terraform-provider-github#415]
* Since the workflow is set to be triggered on the existence of github labels we can adjust workflow runs to be triggered only if a label contains `acceptance-test` with the `if` conditional and fail when a `LABEL_FILTER` doesn't follow the `TestAcc` convention rather than fail when a label doesn't contain `acceptance-test/` as the workflow should not be triggered in these cases from the outset (ex. label = `documentation`)

Example Test Behavior: https://github.com/terraform-providers/terraform-provider-github/pull/413/checks?check_run_id=564737001

**Comment by jcudit** [comment]
This is great, thanks @anGie44.

I'm 50/50 on removing the label-based acceptance tests because they can confuse contributors by failing in this way.  Also, I've seen some tests fail if a PR from a fork is labelled rather than a PR against this repo directly.  I plan to merge your fix but am open to other thoughts on how we can better open up acceptance tests to the community.

**Comment by anGie44** [comment]
@jcudit thank you! i'd have to put more thought into test-triggering alternatives or maybe try to emulate how other provider repos are approaching testing. i'm wondering, is there is a set of tests that tend to "fail if a PR from a fork is labelled rather than a PR against this repo directly" or are they random?
