### ISSUE TITLE
[Feature Request] Organization Secrets

### ISSUE THREAD

**Issue by ejhayes** [terraform-providers/terraform-provider-github#468]
Thanks for rolling out support for secrets in #362. It looks like secrets are now supported at the organization level but this does not yet look to be supported by terraform:

https://github.blog/changelog/2020-05-14-organization-secrets/

API documentation:
https://developer.github.com/v3/actions/secrets/#get-an-organization-public-key

Adding support for this would be greatly appreciated!

**Comment by cj-taylor** [comment]
@ejhayes this looks to require a version upgrade of go-github in terraform-provider-github once Organization Secrets is made available in go-github. I tagged this issue in the Pull Request in go-github where I'm proposing the changes. https://github.com/google/go-github/pull/1532

Once merged and available, I'll take a pass at the implementation in terraform-provider-github to address this issue!

**Comment by nikolay** [comment]
They just merged it, so, the library now support organization secrets.

**Comment by patrickmarabeas** [comment]
Rather than setting a `plaintest_value`, would it be possible to stipulate the env var holding the secret? This would probably allow the secret to remain out of the state file all together.

I'm planning on testing the theory out on `resource_github_actions_secret` when I get the change, but thought it would be good to call it out here prior to any development being kicked off.

**Comment by sc250024** [comment]
Yes please!

**Comment by nikolay** [comment]
Any update?

**Comment by cj-taylor** [comment]
PR for bumping the go-github version is still pending via https://github.com/terraform-providers/terraform-provider-github/pull/475

I have a local branch where I had built on top of that, but until that is merged in, we'll be in a holding pattern here!

**Comment by patrickmarabeas** [comment]
Referenced a PR to add RSA public key encryption as an option to `github_actions_secret`. Since this will basically be the same resource, thoughts? - #495

**Comment by ejhayes** [comment]
Checking in to see if there's any eta on when https://github.com/terraform-providers/terraform-provider-github/pull/475. Would be great to see this functionality available!

**Comment by andrew-waters** [comment]
https://github.com/terraform-providers/terraform-provider-github/pull/475 has taken in the latest `go-github` [release](https://github.com/google/go-github/releases/tag/v32.1.0) which should have addressed the acceptance test failures fixed by @anGie44 in https://github.com/google/go-github/pull/1571.

@cj-taylor hopefully this will unblock you on the functional side of this feature

**Comment by ejhayes** [comment]
@cj-taylor looks like #475 is approved and just needs to be merged in. Think you’ll be able to add your changes in?

**Comment by alexrosenfeld10** [comment]
Wondering what the status is on this?

**Comment by nikolay** [comment]
@jcudit Any ETA on when this will get released?

**Comment by jcudit** [comment]
@nikolay Thanks for the ping. Early next week is likely.

**Comment by jcudit** [comment]
The required `go-github` changes are merged in.  Would ❤️  a PR for this one if anyone has the time.  Will otherwise queue this behind the `v3.1.1` to get an implementation up for review.

**Comment by nikolay** [comment]
@jcudit I am a newbie in this space, but if there's nobody else to volunteer, I can give it a try.

**Comment by ejhayes** [comment]
Thank you @jacobfoard!!!

**Comment by nikolay** [comment]
Thank you! At last! I hope this gets released ASAP!
