### ISSUE TITLE
v3.1.0 has slow performance of github_repository_file refresh

### ISSUE THREAD

**Issue by svenwltr** [terraform-providers/terraform-provider-github#568]
### Terraform Version
```
$ terraform -v
Terraform v0.12.29
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository_file`

### Terraform Configuration Files
```hcl
resource "github_repository_file" "codeowners" {
  for_each = {
    for k, v in local.projects :
    k => v if ! lookup(v, "prp_codeowners_ignore", false)
  }

  repository = lookup(each.value, "github_repo", each.key)
  branch     = lookup(each.value, "github_default_branch", "master")
  file       = ".github/CODEOWNERS"
  content    = "* @XXX/${github_team.prps[each.key].slug}\n"
}

```

### Expected Behavior

It should refresh its resource similar fast as in `v3.0.0`.

### Actual Behavior

Refreshing a single `github_repository_file` took multiple minutes and drains the GitHub API limit. We noticed a lot of requests like `GET /repos/:repoOwner/:repoName/commits/:randomOldCommit`. Therefore it looks like it tried to get data from all commits that exist in the repo.

### References

This issue is similar to https://github.com/terraform-providers/terraform-provider-github/issues/565 and https://github.com/terraform-providers/terraform-provider-github/issues/567 but they seem to affect other resources.

**Comment by ahmadnassri** [comment]
+1 this started occurring on our setup as of upgrade to 3.x

the runs now take 30+ minutes and rate limits are hit every time

**Comment by jcudit** [comment]
Thanks for raising this.  We may be able to leverage GraphQL to speed up `getFileCommit()`:

https://github.com/terraform-providers/terraform-provider-github/blob/9c532df8193907ff250481be9060290f65bedd66/github/resource_github_repository_file.go#L342-L385

Instead of iterating through all commits in the repository during a refresh, we can use a targeted query:

```graphql
{
  repository(owner: "terraform-providers", name: "terraform-provider-github") {
    object(expression: "master") {
      ... on Commit {
        history(first:1, until: "2020-10-05T00:04:52Z", path:"README.md") {
          nodes {
            oid
            committedDate
          }
        }
      }
    }
  }
}
```

This reads:
- given an owner, repository name, branch and file path ...
- search the commit history for the branch ...
- and select the first commit before the current timestamp

We can then query the commit directly using the existing v3 client to find its attributes being refreshed.  We could also augment the GraphQL above to output the needed attributes.

**Comment by ahmadnassri** [comment]
I would caution to test that assumption on using GraphQL first ... depending on the implementation in the API, it might still count towards Rate Limits.

https://docs.github.com/en/free-pro-team@latest/graphql/overview/resource-limitations#rate-limit

**Comment by svenwltr** [comment]
> We may be able to leverage GraphQL to speed up getFileCommit().

Why is there an iteration over all commits in that branch at all? Don't we just need the tip of the branch?

**Comment by jcudit** [comment]
🤔  my best guess is so that we can accurately track the commit author, e-mail and message that was responsible for the file:

https://github.com/terraform-providers/terraform-provider-github/blob/9c532df8193907ff250481be9060290f65bedd66/github/resource_github_repository_file.go#L240-L249

Finding the exact commit that placed the latest version of the file would guarantee an accurate comparison of author, e-mail and message.  However, practically speaking, it seems more important that the file is present with the correct SHA over any other detail.

**Comment by svenwltr** [comment]
It might help to specify the `path` (parameter)[https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-commits--parameters] in the `ListCommits` call. Maybe there is a way to get the latest commit for a specific file without iterating over multiple commits. Even then specifying the `path`, the list can be very long.

We have some old repositories that have around 50k commits. That's 10 hours worth of API requests when iterating over all of them.

**Comment by jcudit** [comment]
Ah, good idea @svenwltr.  I will return with some measurements on that approach as well as a comparison that uses the [graphql query above](https://github.com/terraform-providers/terraform-provider-github/issues/568#issuecomment-712258853).

**Comment by jcudit** [comment]
I believe this was fixed by https://github.com/terraform-providers/terraform-provider-github/pull/589.  Can anyone confirm?

**Comment by svenwltr** [comment]
I will try to find some time to test this.

**Comment by svenwltr** [comment]
Version 4.0.1 does not eat up all rate limit quota and executes without errors. Compared to 3.0.0 the whole run is still 20% slower, but I cannot tell what's the reason for this.

I guess this is because it still fetches a lot of requests. We are managing the GitHub codeowners file with this resource and looking at the code it would still fetch a commit for every time the file got changed.

I am fine if we close this, though.
