### ISSUE TITLE
resource/github_membership: do not remove self as org admin

### ISSUE THREAD

**Issue by caarlos0** [terraform-providers/terraform-provider-github#66]
### Terraform Version

```
Terraform v0.11.2
+ provider.github v0.1.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_membership

### Terraform Configuration Files

I migrated from

```hcl
variable github_token {
  default = "token"
}

provider "github" {
  organization = "my-org"
  token        = "${var.github_token}"
}

resource "github_membership" "caarlos0" {
  username = "caarlos0"
  role     = "admin"
}

resource "github_membership" "otherusers" {
  username = "otherusers"
  role     = "admin"
}
```

to

```hcl
variable github_token {
  default = "token"
}

variable admins {
  default = ["caarlos0", "otherusers"]
}

provider "github" {
  organization = "my-org"
  token        = "${var.github_token}"
}

resource "github_membership" "admins" {
  count      = "${length(var.admins)}"
  username = "${element(var.admins, count.index)}"
  role     = "admin"
}
```

### Debug Output

do not have

### Expected Behavior

Should not have removed myself.

### Actual Behavior

Removed myself and tried to add again.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

**Comment by radeksimko** [comment]
Hi @caarlos0 
sorry for the confusion here.

When you create infrastructure from a config, Terraform saves the [state](https://www.terraform.io/docs/state/index.html) of it into a [backend](https://www.terraform.io/docs/backends/index.html) (which can be a local file). This state more or less reflects how you structured your resources in the config, so that we can later pair pieces of config with pieces of state and understand what has changed (if anything).

While this is helpful in many cases, it may be confusing when refactoring your configuration. In such case it's advisable to use [`state` subcommands](https://www.terraform.io/docs/commands/state/index.html) to reflect your config changes in the state.

In your particular case you can run

```sh
terraform state mv github_membership.caarlos0 github_membership.admins[0]
terraform state mv github_membership.otherusers github_membership.admins[1]
```

and the following `terraform plan` should be no-op.

---

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the community forums where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few maintainers.
